version: '3.1'

services:
  web:
    build: .
    container_name: backend
    # depends_on:
    #   - db
    restart: always
    ports:
      - 3001:3001
  db:
    image: mysql:5.7
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Trybesmith
    ports:
      - 3306:3306
    volumes: 
      - ./Trybesmith.sql:/docker-entrypoint-initdb.d/Trybesmith.sql